version: '3'
services:
  php-apache:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=10000
      - DATABASE_NAME=quotesdb
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=Babylon6$
  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=quotesdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Babylon6$

